### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined 

### ISSUE THREAD

**Issue by JungMinu** [nodesource/nscm#24]
Ref: https://support.nodesource.com/helpdesk/tickets/377
```
nscm report
please wait while we process the information
/usr/local/lib/node_modules/nscm/lib/tools.js:190
 range = range.replace(new RegExp(`^${name}@`), '')
 ^

TypeError: Cannot read property 'replace' of undefined
 at normalizeRange (/usr/local/lib/node_modules/nscm/lib/tools.js:190:16)
 at /usr/local/lib/node_modules/nscm/lib/tools.js:179:15
 at Array.forEach (native)
 at crawl (/usr/local/lib/node_modules/nscm/lib/tools.js:175:36)
 at /usr/local/lib/node_modules/nscm/lib/tools.js:183:9
 at Array.forEach (native)
 at crawl (/usr/local/lib/node_modules/nscm/lib/tools.js:175:36)
 at Object.flatten (/usr/local/lib/node_modules/nscm/lib/tools.js:170:3)
 at tools.getPackages (/usr/local/lib/node_modules/nscm/commands/report.js:34:22)
 at runNpm (/usr/local/lib/node_modules/nscm/lib/tools.js:105:7)
wm727l26750a:NodeSourceTest nasheikh$ 
```

**Comment by JungMinu** [comment]
please take a look @julianduque @nw

**Comment by JungMinu** [comment]
just got the reply that they’re using **Node v6.11.1**

**Comment by JungMinu** [comment]
This issue has been resolved.
